create table if not exists public.booking_medical_history (

  id bigint generated by default as identity primary key,

  title text not null,

  visible boolean not null default true,

  sort_order integer not null default 0,

  created_at timestamptz not null default now(),

  updated_at timestamptz not null default now()

);

create or replace function public.set_updated_at()

returns trigger

language plpgsql

as $$

begin

  new.updated_at = now();

  return new;

end;

$$;

drop trigger if exists set_booking_medical_history_updated_at on public.booking_medical_history;

create trigger set_booking_medical_history_updated_at

  before update on public.booking_medical_history

  for each row

  execute function public.set_updated_at();

alter table public.booking_medical_history enable row level security;

create policy "booking_medical_history_select_anon"

  on public.booking_medical_history

  for select

  to anon

  using (true);

create policy "booking_medical_history_insert_anon"

  on public.booking_medical_history

  for insert

  to anon

  with check (true);

create policy "booking_medical_history_update_anon"

  on public.booking_medical_history

  for update

  to anon

  using (true)

  with check (true);

create policy "booking_medical_history_delete_anon"

  on public.booking_medical_history

  for delete

  to anon

  using (true);

create policy "booking_medical_history_select_auth"

  on public.booking_medical_history

  for select

  to authenticated

  using (true);

create policy "booking_medical_history_insert_auth"

  on public.booking_medical_history

  for insert

  to authenticated

  with check (true);

create policy "booking_medical_history_update_auth"

  on public.booking_medical_history

  for update

  to authenticated

  using (true)

  with check (true);

create policy "booking_medical_history_delete_auth"

  on public.booking_medical_history

  for delete

  to authenticated

  using (true);
