-- ============================================================
--  Equipment Module — Tables + RLS
--  (Schema فقط — بدون Seed / بدون UI)
--  شغّل هذا الملف في محرر SQL في Supabase (SQL Editor)
-- ============================================================

-- ------------------------------------------------------------
--  equipment_sections (الأب)
-- ------------------------------------------------------------
create table if not exists public.equipment_sections (

  id          bigint generated by default as identity primary key,

  title       text not null,

  description text,

  icon        text,

  visible     boolean not null default true,

  sort_order  integer not null default 0,

  created_at  timestamptz not null default now(),

  updated_at  timestamptz not null default now()

);

-- ------------------------------------------------------------
--  equipment_items (الابن) — FK مع CASCADE
-- ------------------------------------------------------------
create table if not exists public.equipment_items (

  id          bigint generated by default as identity primary key,

  section_id  bigint not null
              references public.equipment_sections (id)
              on delete cascade
              on update cascade,

  title       text not null,

  description text,

  image       text,

  visible     boolean not null default true,

  sort_order  integer not null default 0,

  created_at  timestamptz not null default now(),

  updated_at  timestamptz not null default now()

);

create index if not exists equipment_items_section_idx
  on public.equipment_items (section_id, sort_order);

-- ------------------------------------------------------------
--  Trigger updated_at (نفس النمط الموجود في بقية الجداول)
-- ------------------------------------------------------------
create or replace function public.set_updated_at()

returns trigger

language plpgsql

as $$

begin

  new.updated_at = now();

  return new;

end;

$$;

drop trigger if exists set_equipment_sections_updated_at on public.equipment_sections;

create trigger set_equipment_sections_updated_at

  before update on public.equipment_sections

  for each row

  execute function public.set_updated_at();

drop trigger if exists set_equipment_items_updated_at on public.equipment_items;

create trigger set_equipment_items_updated_at

  before update on public.equipment_items

  for each row

  execute function public.set_updated_at();

-- ------------------------------------------------------------
--  RLS
-- ------------------------------------------------------------
alter table public.equipment_sections enable row level security;

alter table public.equipment_items enable row level security;

-- ---- equipment_sections ----

create policy "equipment_sections_select_anon"
  on public.equipment_sections
  for select
  to anon
  using (visible = true);

create policy "equipment_sections_select_auth"
  on public.equipment_sections
  for select
  to authenticated
  using (true);

create policy "equipment_sections_insert_auth"
  on public.equipment_sections
  for insert
  to authenticated
  with check (true);

create policy "equipment_sections_update_auth"
  on public.equipment_sections
  for update
  to authenticated
  using (true)
  with check (true);

create policy "equipment_sections_delete_auth"
  on public.equipment_sections
  for delete
  to authenticated
  using (true);

-- ---- equipment_items ----

create policy "equipment_items_select_anon"
  on public.equipment_items
  for select
  to anon
  using (visible = true);

create policy "equipment_items_select_auth"
  on public.equipment_items
  for select
  to authenticated
  using (true);

create policy "equipment_items_insert_auth"
  on public.equipment_items
  for insert
  to authenticated
  with check (true);

create policy "equipment_items_update_auth"
  on public.equipment_items
  for update
  to authenticated
  using (true)
  with check (true);

create policy "equipment_items_delete_auth"
  on public.equipment_items
  for delete
  to authenticated
  using (true);