create table if not exists public.booking_fields (

  id bigint generated by default as identity primary key,

  field_key text unique not null,

  title text not null,

  type text not null,

  visible boolean not null default true,

  required boolean not null default true,

  sort_order integer not null default 0,

  options jsonb not null default '[]'::jsonb,

  data_source text not null default 'manual',

  created_at timestamptz not null default now(),

  updated_at timestamptz not null default now()

);

create or replace function public.set_updated_at()

returns trigger

language plpgsql

as $$

begin

  new.updated_at = now();

  return new;

end;

$$;

drop trigger if exists set_booking_fields_updated_at on public.booking_fields;

create trigger set_booking_fields_updated_at

  before update on public.booking_fields

  for each row

  execute function public.set_updated_at();

alter table public.booking_fields enable row level security;

create policy "booking_fields_select_anon"

  on public.booking_fields

  for select

  to anon

  using (true);

create policy "booking_fields_insert_anon"

  on public.booking_fields

  for insert

  to anon

  with check (true);

create policy "booking_fields_update_anon"

  on public.booking_fields

  for update

  to anon

  using (true)

  with check (true);

create policy "booking_fields_delete_anon"

  on public.booking_fields

  for delete

  to anon

  using (true);

create policy "booking_fields_select_auth"

  on public.booking_fields

  for select

  to authenticated

  using (true);

create policy "booking_fields_insert_auth"

  on public.booking_fields

  for insert

  to authenticated

  with check (true);

create policy "booking_fields_update_auth"

  on public.booking_fields

  for update

  to authenticated

  using (true)

  with check (true);

create policy "booking_fields_delete_auth"

  on public.booking_fields

  for delete

  to authenticated

  using (true);

insert into public.booking_fields

  (field_key, title, type, visible, required, sort_order, options, data_source)

values

  ('name', 'الاسم', 'text', true, true, 1, '[]'::jsonb, 'manual'),

  ('phone', 'رقم الموبايل', 'tel', true, true, 2, '[]'::jsonb, 'manual'),

  ('age', 'السن', 'number', true, true, 3, '[]'::jsonb, 'manual'),

  ('medical_history', 'التاريخ المرضي', 'multiselect', true, false, 4, '["لا يوجد","مرض السكري","ارتفاع ضغط الدم","أمراض القلب","سيولة الدم","حساسية من الأدوية","التهاب كبدي","حمل","أخرى"]'::jsonb, 'manual'),

  ('notes', 'ملاحظات', 'textarea', true, false, 5, '[]'::jsonb, 'manual'),

  ('service', 'الخدمة', 'select', true, true, 6, '[]'::jsonb, 'services'),

  ('date', 'التاريخ', 'date', true, true, 7, '[]'::jsonb, 'manual'),

  ('time', 'الوقت', 'time', true, true, 8, '[]'::jsonb, 'manual')

on conflict (field_key) do nothing;
